name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Keycloak
      uses: ./keycloak/
      with:
        keycloak_version: 21.1
        keycloak_http_port: 8080
        keycloak_admin_user: admin
        keycloak_admin_pass: admin

    - name: KeyCloak is up
      run: bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8080/)" != "200" ]]; do sleep 5; done'

    - name: CLI keycloak
      run: docker exec keycloak bash -c "/opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin"

    - name: Create realm
      run: docker exec keycloak bash -c "/opt/keycloak/bin/kcadm.sh create realms -s realm=hub -s enabled=true -o"

    - name: Create client
      run: docker exec keycloak bash -c "/opt/keycloak/bin/kcadm.sh create clients -r hub -s clientId=hub -s enabled=true -s clientAuthenticatorType=client-secret -s secret=8eZ8Mq52xiEYJRIkaCz7ffSb0o6sBxkD"

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Prepare the application
      run: |
        php -r "file_exists('.env') || copy('.env.ci', '.env');"
        php artisan key:generate
        php artisan config:cache
        php artisan config:clear

    - name: Run test suite
      run: composer run-script test
