name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Keycloak Admin CLI
      uses: ./keycloak/
      with:
        keycloak_version: 21.1
        keycloak_http_port: 8080
        keycloak_admin_user: admin
        keycloak_admin_pass: admin

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Prepare the application
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        php -r "file_exists('.env') || copy('.env.ci', '.env');"
        php artisan key:generate
        php artisan config:clear
        php artisan config:clear

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
